behaviors:
  CarDriver:
    trainer_type: ppo

    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.93
      num_epoch: 3

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2

    max_steps: 0.5e7
    time_horizon: 64
    summary_freq: 192000
    keep_checkpoints: 10
    checkpoint_interval: 500000
    threaded: true
    init_path: null

    behavioral_cloning:
      demo_path: Assets\Demonstrations\FwdAndBkwd
      strength: 0.5
      steps: 5000000
      batch_size: 512
      num_epoch: 3
      samples_per_update: 0

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2

      gail:
        strength: 0.5
        gamma: 0.99
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
        demo_path: Assets\Demonstrations\FwdAndBkwd
        learning_rate: 3.0e-4