behaviors:
  CarDriver:
    trainer_type: ppo

    hyperparameters:
      batch_size: 512
      buffer_size: 32000
      learning_rate: 3.0e-5
      learning_rate_schedule: linear
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.90
      num_epoch: 3

    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2

    max_steps: 1e7
    time_horizon: 64
    summary_freq: 192000
    keep_checkpoints: 20
    checkpoint_interval: 500000
    threaded: true
    init_path: null

    behavioral_cloning:
      demo_path: Assets\Demonstrations\InitialDemonstra_0.demo
      strength: 0.5
      steps: 10000000
      batch_size: 512
      num_epoch: 3
      samples_per_update: 0

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

      gail:
        strength: 0.5
        gamma: 0.99
        network_settings:
          vis_encode_type: simple
          normalize: false
          hidden_units: 128
          num_layers: 2
        demo_path: Assets\Demonstrations\InitialDemonstra_0.demo
        learning_rate: 3.0e-5
        use_actions: false
        use_vail: false